### ISSUE TITLE
Collected withdraw fee should be renamed and recalculated to include the initial donation

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/augmented-tbc-design#3]
During the initialization the funding poll gains a lot of funds... i would love to see that included in the in this measurement...

Maybe it could be renamed to "Funds Generated for Cause" or something along those lines

**Comment by dapplion** [comment]
Fixed with https://github.com/dapplion/augmented-tbc-design/commit/dfeda20a04b795eb01503ada19ae45a8c527c229.
Right now the funds generated via the hatch are 2 orders of magnitude bigger than the fees, so showing them bundled would make impossible to tell the portion of the fees. I'll leave them separated by now but renamed as you suggested.

----

![fundsG](https://user-images.githubusercontent.com/35266934/62427665-a8b2a200-b6f6-11e9-91d7-0e7dc0caa660.png)
