### ISSUE TITLE
We need more tool tips on each parameter

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/augmented-tbc-design#6]
I need to write that out here

**Comment by dapplion** [comment]
Added a popover on click for each parameter, both inputs and results. The descriptions are the same as the bigger description shown if clicking the (?) symbol for consistency. Fixed with https://github.com/commons-stack/augmented-tbc-design/commit/cce04ea80ec85db286791d326fc147ae8c780612

----

![single description](https://user-images.githubusercontent.com/35266934/62824108-94105700-bb99-11e9-9bba-adfff311584f.png)
